#!/bin/bash

container_name=$1
shell=${2:-bash}  # If $2 is empty, default to "bash"
user=$3

if [ -z "$container_name" ]; then
    echo "Usage: docker-sh <container_name> [shell] [user]"
    exit 1
fi

if [ -z "$user" ]; then
    docker exec -it "$container_name" "$shell"
else
    docker exec -it -u "$user" "$container_name" "$shell"
fi
